### ISSUE TITLE
Non Type Error

### ISSUE THREAD

**Issue by ShadowVicky** [silverriver/OOD4NLU#2]
config['word_vocab_size']=min (config['word_vocab_size'],len(word2id))
typeerror: object of type 'NonType has no len()

why i am getting this error and how can i fix it?

**Comment by silverriver** [comment]
You word2id dict may be empty. Did you prepare the vocab file first?

**Comment by silverriver** [comment]
@ShadowVicky hi, I am wondering have you fixed this issue?

**Comment by ShadowVicky** [comment]
@silverriver yes.Thanks for your help
